### ISSUE TITLE
Entry Point Not found

### ISSUE THREAD

**Issue by caganer** [nadhirxz/magnet2torrent#1]
Windows executable on Windows 7 Professional SP1.
Used sendto to send executable to cmd prompt and added a magnet link without arguments, first without encapsulating quotes on the magnet link and then with. Same result in each case:

"Entry Point Not found
The procedure entry point GetHostNameW coud not be located in the dynamic link library WS2_32.dll".

No prompt from firewall to permit or deny network (WAN) access appeared which is its customary behaviour for new applications seeking internet access.

**Comment by nadhirxz** [comment]
1. Passing arguments without encapsulating quotes on the magnet link does not work for CMD. Magnet links mostly contain the ampersand (&) which is a special character in CMD, so you must either escape the ampersand by using the caret (^) symbol, or you must enclose the string inside quotation marks.
2. As for the error "Entry Point Not found", Windows 7 reached it's EoL (End-of-Life) phase already as stated [here](https://www.microsoft.com/en-us/windows/windows-7-end-of-life-support-information), so NodeJS dropped it. So we can't publish builds to any of the other operating systems that their vendor has expired support for them as stated [here](https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list), not just Windows 7.
> Node.js does not support a platform version if a vendor has expired support for it. In other words, Node.js does not support running on End-of-Life (EoL) platforms.
